apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-init
  namespace: vaultrix-prod
data:
  init.js: |
    db.getSiblingDB("users_db").createCollection("init");
    db.getSiblingDB("orders_db").createCollection("init");
    db.getSiblingDB("wallet_db").createCollection("init");
    db.getSiblingDB("invoice_db").createCollection("init");
    db.getSiblingDB("review_db").createCollection("init");
