apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: vaultrix-prod
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: "root"
  MONGO_INITDB_ROOT_PASSWORD: "vaultrix-secure-password" # TODO: replace
