# Identity
nameOverride: ""
namespace: "vaultrix"
appName: "user-service"
component: "backend"
partOf: "vaultrix"
environment: "dev"

replicaCount: 1

image:
  repository: "REGISTRY/vaultrix-user-service" # TODO: set your image registry
  tag: "latest"
  pullPolicy: IfNotPresent

imagePullSecrets: []

serviceAccount:
  create: true
  name: "user-service"
  annotations: {}

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  name: "user-service"
  type: ClusterIP
  port: 3001
  targetPort: 3001
  appProtocol: http

container:
  name: "user-service"
  port: 3001

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

probes:
  liveness:
    enabled: true
    path: /health
    initialDelaySeconds: 15
    periodSeconds: 10
  readiness:
    enabled: true
    path: /health
    initialDelaySeconds: 10
    periodSeconds: 10

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

config:
  enabled: true
  mapName: "user-service"
  map:
    PORT: "3001"
    WALLET_SERVICE_URL: "http://wallet-service:3003"


secret:
  enabled: true
  create: true
  name: "user-service"
  stringData:
    MONGO_URI: "# TODO: set MONGO_URI"
    JWT_SECRET: "# TODO: set JWT_SECRET"
    INTERNAL_SERVICE_TOKEN: "# TODO: set INTERNAL_SERVICE_TOKEN"


httpRoute:
  enabled: false
  name: "user-service-route"
  parentRefs: []
  hostnames: []
  rules: []
