# Identity
nameOverride: ""
namespace: "vaultrix"
appName: "order-service"
component: "backend"
partOf: "vaultrix"
environment: "dev"

replicaCount: 1

image:
  repository: "REGISTRY/vaultrix-order-service" # TODO: set your image registry
  tag: "latest"
  pullPolicy: IfNotPresent

imagePullSecrets: []

serviceAccount:
  create: true
  name: "order-service"
  annotations: {}

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  name: "order-service"
  type: ClusterIP
  port: 3002
  targetPort: 3002
  appProtocol: http

container:
  name: "order-service"
  port: 3002

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

probes:
  liveness:
    enabled: true
    path: /health
    initialDelaySeconds: 15
    periodSeconds: 10
  readiness:
    enabled: true
    path: /health
    initialDelaySeconds: 10
    periodSeconds: 10

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

config:
  enabled: true
  mapName: "order-service"
  map:
    PORT: "3002"
    NOTIFICATION_SERVICE_URL: "http://notification-service:3007"
    USER_SERVICE_URL: "http://user-service:3001"


secret:
  enabled: true
  create: true
  name: "order-service"
  stringData:
    MONGO_URI: "# TODO: set MONGO_URI"
    INTERNAL_SERVICE_TOKEN: "# TODO: set INTERNAL_SERVICE_TOKEN"


httpRoute:
  enabled: false
  name: "order-service-route"
  parentRefs: []
  hostnames: []
  rules: []
