# Identity
nameOverride: ""
namespace: "vaultrix"
appName: "notification-service"
component: "worker"
partOf: "vaultrix"
environment: "dev"

replicaCount: 1

image:
  repository: "REGISTRY/vaultrix-notification-service" # TODO: set your image registry
  tag: "latest"
  pullPolicy: IfNotPresent

imagePullSecrets: []

serviceAccount:
  create: true
  name: "notification-service"
  annotations: {}

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  name: "notification-service"
  type: ClusterIP
  port: 3007
  targetPort: 3007
  appProtocol: http

container:
  name: "notification-service"
  port: 3007

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

probes:
  liveness:
    enabled: true
    path: /health
    initialDelaySeconds: 15
    periodSeconds: 10
  readiness:
    enabled: true
    path: /health
    initialDelaySeconds: 10
    periodSeconds: 10

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

config:
  enabled: true
  mapName: "notification-service"
  map:
    PORT: "3007"
    SMTP_HOST: "smtp.gmail.com"
    SMTP_PORT: "587"
    SMTP_SECURE: "false"
    SMTP_FROM_NAME: "Vaultrix Support"
    SMTP_FROM_EMAIL: "<redacted>"


secret:
  enabled: true
  create: true
  name: "notification-service"
  stringData:
    SMTP_USER: "# TODO: set SMTP_USER"
    SMTP_PASS: "# TODO: set SMTP_PASS"


httpRoute:
  enabled: false
  name: "notification-service-route"
  parentRefs: []
  hostnames: []
  rules: []
