apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: vaultrix-dev
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: "Vaultrix@123!"
  MONGO_INITDB_ROOT_PASSWORD: "Vaultrix@123!"
