replicaCount: 1

image:
  repository: ghcr.io/vaultrix-in/review-service
  pullPolicy: IfNotPresent
  tag: "a900b"

service:
  type: ClusterIP
  port: 3005

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 10m
    memory: 64Mi

env: {}


imagePullSecrets:
  - name: ghcr-login
