apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: vaultrix-storage
provisioner: kubernetes.io/no-provisioner # TODO: Change to your actual provisioner
volumeBindingMode: WaitForFirstConsumer
