replicaCount: 1

image:
  repository: ghcr.io/vaultrix-in/wallet-service
  pullPolicy: IfNotPresent
  tag: "6e942"

service:
  type: ClusterIP
  port: 3003

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 10m
    memory: 64Mi

env: {}

