environment: "prod"
namespace: "vaultrix-prod"

secret:
  stringData:
    MONGO_URI: "mongodb://root:Vaultrix@123!@mongodb.vaultrix-prod.svc.cluster.local:27017/orders_db?authSource=admin" # TODO: replace <password>
