replicaCount: 1

image:
  repository: ghcr.io/vaultrix-in/order-service
  pullPolicy: IfNotPresent
  tag: "0e2af"

service:
  type: ClusterIP
  port: 3002

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 10m
    memory: 64Mi

env:
  PORT: "3002"
  USER_SERVICE_URL: "http://user-service:3001"
  NOTIFICATION_SERVICE_URL: "http://notification-service:3006"


imagePullSecrets:
  - name: ghcr-login
