apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "review-service.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
spec:
  encryptedData:
    # Encrypted placeholders - Run the following commands to update these:
    # echo -n "VALUE" | kubeseal --raw --name {{ include "review-service.fullname" . }}-secret --namespace {{ .Release.Namespace }}
    MONGO_URI: "AgBXaeCT4ZNHFW6okFgk7S2fcTfK5ssC8p/XTon6OxIWKyB5KlETyq3pCBUVl5NnuIW2P1c95GMFeFvdHwwKknQ/Toj/7Q1SLY+2Rh7Mm1+hwjK6mcewJIAaD249VKquN1AzAmxUTQxk5Dyucu+egKsxtzKVTLHEE1iNJ1JsrXWQhNOCAUgvB//hCWKA4jE/2NEgjuU8iG+VGpFS77KPMNExkQmDmgtoaZyKUSX+X00YcPJyaCkNtvU4YFFATQFwR6PMm1u5g4mJgSbR2oWlh6RWdB3HM5yz+ncsh9LWsshrtcCMxeSb8YSjJKB30hGKY9nye7fxOxspRG9uD3CGuNf3QwtVC1v7ugzstLXizSSiX9ZwaAESCrq3Fn/ZPKHWXrWIToA2CP9TUI9Q701Q6TFqRRowdhyq655y5IMbfGkC/EnL/cPYD2/vNHtdnKZ6b/T1i1P0gIMDWMTBOomz1zbUUxMUFd+eotAU+cV+QCfAkUdVRoEX2PXjJZBp+/w91SDEL+Y/KZyZoX0t8a82Q3z2CWzSXKcgajBHDtU5wDdueFdhsaHqGMTjPey+nv27u4UFN/GbW+O9qgTfbmQS9TwsenPmBZg+6ZM41gpbHgkNosyyW8elLKuMaQFOQMjND381vOMVR14bGOR6blJZ+LEW0kTTX0TtukEOiUGsYZbsaPvpbfc3/wLIaIFbaYgtOm8A2VBqVQS5IopTeD4HyYOCQwNUQWsV8jJ2HmAHPNUf1S4wD0s3lFMuseW74smn63jBPKlbLsgUedKz8yCZnsMehIZM5B5BQ++tanMJxSY="
  template:
    type: Opaque
    metadata:
      name: {{ include "review-service.fullname" . }}-secret
      namespace: {{ .Release.Namespace }}
