apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "review-service.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
spec:
  encryptedData:
    # Encrypted placeholders - Run the following commands to update these:
    # echo -n "VALUE" | kubeseal --raw --name {{ include "review-service.fullname" . }}-secret --namespace {{ .Release.Namespace }}
    MONGO_URI: "AgCeeq/E2Su0N/qCEhfmffoyDeGqLwuXaidGNO1PR3v1fmj1T180GMCylNJv4nQP/e+Mf7xY5LEaBM/7YS2gPNStUFmqzqxs4wjK46YxOmnjHxBD10n68pY/t30tsav5o2dLpeuEhD19vIBZoS07L/EE6/5GpCo5BHa3Ffa41qfrHsqLVoQzVZ0ihQr7JT7v97UX+AYaHlE//vOmyt0LBGDqRgFFjndk97qHhlw0ZpS7DzT8pTsHof2FL+BS32Mf4akJ09jRNusj6dDc1BqYVU3H+29UHy6La3gHBgbf6QAnz3cNWQG4nk82VPtUdKfJYUtk64njae6dnGdowwzELOhQv6N+D9Gzdw2wYR422c6SSpDxnZqZDSPKYILns3Q1wjw6PbemkQv/tSrP9N7Szyqf/qmy6PW5wtupC4NhHeW4X2F8xfj8hIS8o1fALAzUFoVNjWoj/43XnkkPtbJLdmCMTxjfaGTs5KkuDvpJ7CshQQmZnUNK2mswIS9RlBMKBDGfKMVYgFM86miyM/NKEgu1Zg9P6zBALgRnhBuDgFmDE6NpwHUmOYSk3V8oCW/uzTxvkb/QvJbhuoCPsPKCPshhhWyH5nFcIOxfO/Lq6WNjXdkg3eQ2x2olecnH5aaNrCVM/tM85LiKQtVvU0UTWxkHLLNJyM+80k3OMZfeteGRwoSFVPz6iJCsUt0E3aMOviVY+KlL3csH7G/uxmBfsvyWPKCDPOz/8Urlmz2fp43ZR1eDp2Q9f3KWUlDAIONG1n49ew17qQytW5wMzVTL8tMalOSTzgOhxorKqEjPsusqKIjrzrTxpQ=="
  template:
    type: Opaque
    metadata:
      name: {{ include "review-service.fullname" . }}-secret
      namespace: {{ .Release.Namespace }}
