replicaCount: 1

image:
  repository: ghcr.io/vaultrix-in/invoice-service
  pullPolicy: IfNotPresent
  tag: "79dca"

service:
  type: ClusterIP
  port: 3004

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 10m
    memory: 64Mi

env: {}

