# Identity
nameOverride: ""
namespace: "vaultrix"
appName: "api-gateway"
component: "backend"
partOf: "vaultrix"
environment: "dev"

replicaCount: 1

image:
  repository: "REGISTRY/vaultrix-api-gateway" # TODO: set your image registry
  tag: "latest"
  pullPolicy: IfNotPresent

imagePullSecrets: []

serviceAccount:
  create: true
  name: "api-gateway"
  annotations: {}

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  name: "api-gateway"
  type: ClusterIP
  port: 3000
  targetPort: 3000
  appProtocol: http

container:
  name: "api-gateway"
  port: 3000

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

probes:
  liveness:
    enabled: true
    path: /health
    initialDelaySeconds: 15
    periodSeconds: 10
  readiness:
    enabled: true
    path: /health
    initialDelaySeconds: 10
    periodSeconds: 10

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

config:
  enabled: true
  mapName: "api-gateway"
  map:
    PORT: "3000"
    USER_SERVICE_URL: "http://user-service:3001"
    ORDER_SERVICE_URL: "http://order-service:3002"
    WALLET_SERVICE_URL: "http://wallet-service:3003"
    INVOICE_SERVICE_URL: "http://invoice-service:3005"
    REVIEW_SERVICE_URL: "http://review-service:3006"


secret:
  enabled: false
  create: false
  name: ""
  stringData: {}


httpRoute:
  enabled: false
  name: "api-gateway-route"
  parentRefs: []
  hostnames: []
  rules: []
