{{- if and .Values.secret.enabled .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name | default .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "invoice-service.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- range $key, $val := .Values.secret.stringData }}
  {{ $key }}: {{ $val | quote }}
{{- end }}
{{- end -}}
