apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "order-service.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
spec:
  encryptedData:
    # Encrypted placeholders - Run the following commands to update these:
    # echo -n "VALUE" | kubeseal --raw --name {{ include "order-service.fullname" . }}-secret --namespace {{ .Release.Namespace }}
    MONGO_URI: "AgCH0YoEetbk2KgWjpLRU0cbICg47ej8ayAZ43iq0Lycn0IxDUdDZ+hiDLepE2nR5SAdJ9qMK0lWEwSV2FRnf4VWlcd3A6VHW0GeDZsjyYbYVI/0FkpN3a3az3tqNJ9QAVEEG8JhsmmWTqL82t56DcgeUjbllXVVmGO333u3G5idNBYODiJTfx51fuCvHAnQgMBL0WfX/S+3lfFBfoRcPLcrjPuTYpI16Fsn3T4OJQ+wEuB7YPHGN0n4qX0JemHD9PSs/FiqDr6U6XfbHTxqnaV6guLKCSfzevkSok3d9p1b0VgH7pIMKCSkkdqoqB0Vj9HJKUDxauFVMwMBWtt+2HByFl0tojbXNBmz9oIDBRxQvipkEWOEXBEJHLjzgWhXX43xqqLuMfLTKXrNG2OUjO2YZC26Afcnb64bbqddk7mGQWj9FmGYhIZ/kJdQ5HKRsTI36PjB4oE6QzhcOA3U1c8TGI/mdagwtJuoB5WA40w671UeO9N5fKrXU0ZKdyePXfV4ScTqHnmp9YktkO185nmoeft6rTNUy8dJdS8bweslJCyP7VdlnQ0Y6VqJfWWKEyTrJj5c44o5REk5xOHi5vPPs5DKZpTA/ymi6qZUM8xyOwQKJtxKqutIinNhSqvNTf8pL4r3k124LcacgtMDI5sRaA+qORceFut71s5r36dx8hxuxSAPXXYdH+cwdOXGHhw6ygNP7qjY3gCsHm2yiqUHa9tZ16B5uOj2TFX8EUMBOBXGbLe4TXisGz6DQjHqCpOm1raFDw2XpXUZr/4a310wGb3XhNycN448KJeKJwIDVTntuf+Ypg=="
  template:
    type: Opaque
    metadata:
      name: {{ include "order-service.fullname" . }}-secret
      namespace: {{ .Release.Namespace }}
