apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "order-service.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
spec:
  encryptedData:
    # Encrypted placeholders - Run the following commands to update these:
    # echo -n "VALUE" | kubeseal --raw --name {{ include "order-service.fullname" . }}-secret --namespace {{ .Release.Namespace }}
    MONGO_URI: "AgAZI9uiQ21nPr5hqrAPJ1xQf91Kqb27ch9Yl7TSAi1T/nCNd2bTvFNYhib3JWx8TdDF3YS2QIN1WvRwGu8HA/w7ljVGVX4mN8DeE67fmq26vDtqAnrBfxbxCvztIhtbHjm6jg0mr14SMKLdUEz54nExlcDYFx35EwI/bNUUiM1i3Hru0Q8m/1Kiwc47zRPtd4cj0J7AIuWreD/lfIEI04Bkvv+az410i/4nWVqqM41+EkWbQgu3mhrxAAPKQaVcvdVKv+TMzEMXy6K6K7qaosAbtitQA4IVTKfm7/gufuOlXgeAMj8gYbmuW/mX9xrWZGc6zSCW1doDNnpEKh7IcDJsyJvnUxus9YsIzPsKmpXElazpzGjgfBDIXE/u5aukcYGEk/92TAz1t2XDMqOYkNzoxpzCCOkj0rrvJPon6no60j0HdmS0dMMB15DIo5pJISU+LMOtMKDKizt8oRWWNzFUTxFu6AzzBPkpcp3CeU8JMq/USNrAsu2kVzgFiqaDmGT0SdMvRlo6dhRu7wMfw7GrVpcdQb9HnqnIS0ehxr/eMzyG7XohQEBNFMsuLM1E0oOxMOpNltul+cRCPqZ7nDDE+tlfpJkpMfGP0wmcF9cF80Rpas4ULGQVm33rgiA5N2FWuHHwx04x3Ktvq3fuEfkHCdHAYSx/noWxPmQ3agsU9UbKTjCL5iuvYauBFUK1KGhwPyB/HfsBhV0037D3nSSsBgdWhhX+QyNoBqwj51E3mYPCh6pac5tWUtnpzNcbPSp663fbhRgTnvpia7XSqQGmsg1wDt4z2iBRIpb9+do="
  template:
    type: Opaque
    metadata:
      name: {{ include "order-service.fullname" . }}-secret
      namespace: {{ .Release.Namespace }}
