apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "order-service.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
spec:
  encryptedData:
    # Encrypted placeholders - Run the following commands to update these:
    # echo -n "VALUE" | kubeseal --raw --name {{ include "order-service.fullname" . }}-secret --namespace {{ .Release.Namespace }}
    MONGO_URI: "AgAJCx/sNmIhKUpAfdx/6yzaI5JSSfnZAduL/iSjvNn6mijjvYXrw2nVWg6riTGumZz9QPOcip6mQA5w0kiufIaMwuVil5n5WxrIZJVmS+FU7n9RFj8qQiLWdn3BQldMV4Ed2DTq1gt4Who54u6nn3lCuAJF0mvhFY31DJgwuAhJvR7lNUswuXmQAwIDSEniF1wHe5uBQ5vpKEEYgSyWNE6q1TEdyJ2i14a0lrOWcNwTbaZBOuTReDEjNKRrdEph8sCmKhhhiyHgfk6sPv6Bc5ulqCi/97NuXVp+kJHyfyEXLw+vSMN0s5g1tqYluCLWm6zJBe/8zEOijvi0alLn3AaADnr1+Qs3/nO1bZkOpnK6jf5FNRiB7J04yvSHajPkFURq5Hj5oJpwFnVzxon93cSUIOPMBRQ/JchmvcZt8vl9LfsmoytR09NbRI0GVRiWu/P3hnpSymG3F4Ws/LxPcuSmZFx//Ik6p1b73RfmrkDboE/T14ItEqHun1u3SDaEeYXfogLuo7bPQQEMFkjQtnMB1sHZhKYDlMxBtGnUkycQkKR3nV6m8lRcgB7QvI8pcqO26/ns+OPfQupufaT+rL3H+gr9vWvcZ6/d3SlnRNrEf1dwiuSLLVBv8osJMQsmI42m2CgIi1Bamai6IyoeEEHpfUvR+EYBShL1ZpJII7PifWhHXGPnQG8EcDwgKASonf4duVRaJy4FOEIZDsp06fYVSVVy37FuvK6BOTiRkUGV91M4/3ZEFKkaf5ARvs7Gv1fmRJCCDIOB1GhiRkqyeF7FsAxsDcylmQ=="
  template:
    type: Opaque
    metadata:
      name: {{ include "order-service.fullname" . }}-secret
      namespace: {{ .Release.Namespace }}
