# Identity
nameOverride: ""
namespace: "vaultrix"
appName: "invoice-service"
component: "backend"
partOf: "vaultrix"
environment: "dev"

replicaCount: 1

image:
  repository: "REGISTRY/vaultrix-invoice-service" # TODO: set your image registry
  tag: "latest"
  pullPolicy: IfNotPresent

imagePullSecrets: []

serviceAccount:
  create: true
  name: "invoice-service"
  annotations: {}

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  name: "invoice-service"
  type: ClusterIP
  port: 3005
  targetPort: 3005
  appProtocol: http

container:
  name: "invoice-service"
  port: 3005

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

probes:
  liveness:
    enabled: true
    path: /health
    initialDelaySeconds: 15
    periodSeconds: 10
  readiness:
    enabled: true
    path: /health
    initialDelaySeconds: 10
    periodSeconds: 10

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

config:
  enabled: true
  mapName: "invoice-service"
  map:
    PORT: "3005"
    ORDER_SERVICE_URL: "http://order-service:3002"


secret:
  enabled: true
  create: true
  name: "invoice-service"
  stringData:
    MONGO_URI: "mongodb://root:<password>@mongodb:27017/=admin" # TODO: replace <password>


httpRoute:
  enabled: false
  name: "invoice-service-route"
  parentRefs: []
  hostnames: []
  rules: []
