
frontend:
  enabled: true
api-gateway:
  enabled: true
user-service:
  enabled: true
order-service:
  enabled: true
wallet-service:
  enabled: true
invoice-service:
  enabled: true
review-service:
  enabled: true
notification-service:
  enabled: true
