apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "api-gateway.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
spec:
  encryptedData:
    # Encrypted placeholders - Run the following commands to update these:
    # echo -n "VALUE" | kubeseal --raw --name {{ include "api-gateway.fullname" . }}-secret --namespace {{ .Release.Namespace }}
    JWT_SECRET: "AgCNnMkx/+PQK/A8hcL5TKG1OeRMzLxantFQhI2JN7Men/ud/VZabmNIL4dF5fM0zkWCZapp6Cd086FFkPpWb5COAYFNHDZsw0LlOgGjyTpFMTybOL2TrmkU+BNGtW6r4HezNDEuROseC+pz9xA6Gro3N/n0HSOt61REUDq5pqOg34IDRVC6WnthD+pwQ+AGxOiYtWuYxMfKzZvaSDd376jwRpLUCanbhy/3pAYr8PU1r2r+sFtnFOj95szpDYffnJK+d/zDRBxpZ3PkaMrb9d8U1dTEWIvWqYoBHEld2wO+IfVhRPqYFIWTvD5tqEOTnF4cMTQOVncLczWa52MDoVubV2UkH1OvBtP093LYVrkx/fx9X/xCEhQiLrOV3Gxhuy9iJLSUNuDbc46zqM16JT1axaKuy0vdIwzA0mw397ah2kh/NEskFSb2fJpYxzCD6XUa9gkdBdne84d6lzhXN8JFmbTh63IZbTeIIbydt/p2jtGGEc4bYZGDlv9GpmioYqo/X/zJTDwGAlZ/gwmrZnPucMGUhHkqJiiiGa2aT8j7CZdnmxkBGuimNre2BIuUx9QB/kcRo4QES31s1C9A8tpGqOr315L+vYeHT9wmBKTw9REGLGDbbjo02gJfYU1mBwTt9qwos6Y16YZzqI4d813zw//IK/GWvFTaitJmHaYyVRO+MEEhO273WPAtBAifQgw+xqyIMgGDOby+T6Ig"
  template:
    type: Opaque
    metadata:
      name: {{ include "api-gateway.fullname" . }}-secret
      namespace: {{ .Release.Namespace }}
