apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "api-gateway.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
spec:
  encryptedData:
    # Encrypted placeholders - Run the following commands to update these:
    # echo -n "VALUE" | kubeseal --raw --name {{ include "api-gateway.fullname" . }}-secret --namespace {{ .Release.Namespace }}
    JWT_SECRET: "AgBZujKG2gCqYnKt79N7SeO+BYFFaqH5nv4XWR5wmYzVwPexbE+9cWa3R4Ceahas+G/9okLaz6N1sQZwPgApek+JMVJln2JV6/4DCzK1op/yAEizjNgKSkVHQoEPN32C3XU6TC8qM7un0OMykzq2NGWecGlDNbUguFTxGhdAtDHneBdEfH99xfkNRVx3dXx1H+dGplC6Drx9iPtxdvz61pTGqC6vvcL5LbpRTOEqPklwgmfd4RibKULhKkFlgzVw4ZZT8rITQW0ZHMEQe2JO5csP/zZbfbRa3S6NGK0TTDptK/YKuG+zonEi7LGHRqLRC3PkHks6mlkNTFyxiO5EIRgsCdHUT8xr9kNHKBsj5gnj0JbGAIHTSQL1raB8lZMwav9yDP6CHhTEkFvT9y9I0apRo1yuQItKznBqUVT+E+zaCvatN2x2/XcIS1aIzbyf8MWa8+hj8NeZhhE9Q1qHwZ2EzmldcY6a8b8TAGmbhLpSRWlsYbUw3+GxHRzO+fOWzSUZ1Ko1Yi4SGgJ1qkXRZbK9D94ODwuATsWhT+smUDuLQLAj7f1Kdb0Bt+Czl7/TD7bQxG9wpf78cwAQh4UO/ch93ngBw+0yhdYStPK6VFQFTAKFC+LrWRi+zlZ0ZLPIyr7s0BJm+cMXgIlWIczoUqyeNZlKk/Tq4ibNZUAuYIzAbx1Wt7M54+xhrYtbqesQN/FWS0QPh9sFqUbCuA=="
  template:
    type: Opaque
    metadata:
      name: {{ include "api-gateway.fullname" . }}-secret
      namespace: {{ .Release.Namespace }}
