apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "api-gateway.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
spec:
  encryptedData:
    # Encrypted placeholders - Run the following commands to update these:
    # echo -n "VALUE" | kubeseal --raw --name {{ include "api-gateway.fullname" . }}-secret --namespace {{ .Release.Namespace }}
    JWT_SECRET: "AgCBYNr4OMb6FwtC4/5Is3sRNmW5p5Md2vt6drHyIMCTDEudcmkUXNs/fnBB/D/dKMiWQiGow4jM6l4YFW23Vswc8sWKLw8YobG48f7+97FtDoRsfVd55OG969owh02fhosE6oKxECuUI6IieMkB0Ofh+tJkkKHX0RDBW+90vtGPmkB6nF0Hz5/LwliYJ/jVIaMoERRY/IDAWOW9yePwwYdZnsZ3H21+JRyQRLqd7iOH10iDNdoY3i5v8LSZhvrbIrqNGkWdHWfT2u4MRswlhwEjR9B0AbNbGeqF7e5RlU9ho59PRhRlZCjpzN1wNXu8Bj4K174xHPP02V6Bn4MEBFbt25RJiLeK9O3/05HSxPAtYRySx46HFSimHeGx1YND4lPt+NOQgAt4Skdp0Z/Pu5k3uh8+VbEeJj8D+cOA3QGKZ9tAYEYsGiIj7feP+E1yGvE94x2NBGLGZavI8rhrgk6XBT84LjndW9CuVullkGig2wgLso0ohJmWc9dx9LVXXAmBFoXONefOJSWKUHfVmOGhOJ5VygdXUuB0hmvq77IITIjeOBo/Bb6gX/TmNn29+4X6hMUPZE75paEkzh5Rnm5qMEjhMj71G2yTp0pE4xyLqnsMvwWEN0mXm5CN7khRKGlzSWVidIzmpywXdo075pkP3ye09UqhzMBLeJWJWNSrTjT+eVMmgeZogKz9iIDYgmLlHdvk7SKvSKK+nw=="
  template:
    type: Opaque
    metadata:
      name: {{ include "api-gateway.fullname" . }}-secret
      namespace: {{ .Release.Namespace }}
