apiVersion: v1
kind: Secret
metadata:
  name: {{ include "frontend.fullname" . }}-secret
type: Opaque
stringData:
  {{- range $key, $val := .Values.secret.stringData }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
