apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml
  - mongodb/secrets.yaml
  - mongodb/deployment.yaml
  - mongodb/service.yaml
  - gateway/gateway.yaml
  - gateway/httproute.yaml
