namespace: "vaultrix-dev"
environment: "dev"
replicaCount: 1
image:
  tag: "latest"

httpRoute:
  parentRefs:
    - name: shared-gateway
      namespace: gateway-system
      sectionName: http
  hostnames:
    - vaultrix.test.internal # TODO: set your actual test hostname
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: frontend
          port: 80
