{{- if .Values.httpRoute.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.httpRoute.name | default (printf "%s-route" .Values.appName) }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
spec:
  parentRefs:
    {{- toYaml .Values.httpRoute.parentRefs | nindent 4 }}
  hostnames:
    {{- toYaml .Values.httpRoute.hostnames | nindent 4 }}
  rules:
    {{- toYaml .Values.httpRoute.rules | nindent 4 }}
{{- end -}}
