apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "invoice-service.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
spec:
  encryptedData:
    # Encrypted placeholders - Run the following commands to update these:
    # echo -n "VALUE" | kubeseal --raw --name {{ include "invoice-service.fullname" . }}-secret --namespace {{ .Release.Namespace }}
    MONGO_URI: "AgBSNMNOGZ7PzvRWNOYKF7f/GScE0X+4Fw/ZX+RipZ2IPQApb8e/B7fO8wuzxl1h3KgP73wB7WI/UUseSZSUeKtUAzUKBE7SUS/xnfRdh2JwRdIo+WL9nYcr8hLPI1pIKy7zN9yl6O4+UVjp0dd82U14frHPKA7NKuEeWHoqD4Gq43fQrFn8v/c5foPEirO0kQrVMS2MgJ9T4XQ6opc622T5pL8HztRCIgYPRuABStP2x6lztvSQxk/FncBq/l9G67s/hwmfM5KKcm8eGy0yM9poSJTWSFUpi14bj9qEqcuDx3dABWEXbWoa1aFBLxpMvSbmOnIYH6a5/9XzqmNtRrrynDaoN8bH02F5Faj3pAyotP0zbIGv9I4Nvy+PzWEs04IBu5ehSC3Iq80upokHlajGbR3TeLS2KEBeMlbqGZMHx+DBmGmCnWlL3KVHN1jr9IkuaPCHNW8+WufbE02P41xPpU57NDgwLg6H6tsdQ9XK/yr4TGfe/BijM4Qpl2YDlVruzsXaZwSO1FxjgnSl2uKlhD99MvfdICXnDpR1rYWFUTIMpEhYdjVbFOOuKl4Mn3cmGmonHJR7yf2LfyWx66SGuKzY/VDwLFkIir6OovlJzBeyNkBXd04o48Nr9WNj2PBVOdo4hePbXLmcY3fmZD5Zgrq8rk07j3VfmxTu+hcW7ykhLcrrgedivQdCL8dOmEqrxzcp+8d1avMiNseH8LJetqC8qULxMo5xyePRCH615FlnsqHBPH3j5Cz9zXAePq1tBiQujJI8afzBgBFcVuF+SaKWtn4vQBA="
  template:
    type: Opaque
    metadata:
      name: {{ include "invoice-service.fullname" . }}-secret
      namespace: {{ .Release.Namespace }}
