apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "invoice-service.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
spec:
  encryptedData:
    # Encrypted placeholders - Run the following commands to update these:
    # echo -n "VALUE" | kubeseal --raw --name {{ include "invoice-service.fullname" . }}-secret --namespace {{ .Release.Namespace }}
    MONGO_URI: "AgBQA6RwshHcGADdBDp0JFd2CyFKX1HQNaRQAYwyeQvGbX2EKLaTbk8GNGz4Awshh4fs0QF6Z/oSZA/fg60FTPIST2lCdqliLIbzNwWlJiGZHG8wZc4Hc8hOBB+sD7FY5vWiUG48vla7yGPmkbeMsgcqYShx+hTRcF4pxdgYtT37gZWnCudkDGhBhqcL/9Uc5+6FAl1TF4wxTa5KZBB5dpCP3n7+CJj2sBoFYzpHp4Rrrgm4qLbXl+gD6+TFRjaoPYI6brb3DQfHUVLzeZBpL1bRQo0fxmN/wJXx2UKnDChEJTo6xvWZMDkbDLIrdxj5nBQfo1jlDOAQzPLg5B3c6YcnIUrEb6Uah760RMq/ESnkoiFIMWGo1vjD7Dh8bWzuUMH3b+WR/lOiibA/ZevKEjuaiMpre/mg1lM3jqQiofdfH/TTSKz89CIuoU0N2xKfEQokZrINkShoXikYkRzyCA2dNn+jjDF9SvxMM0/ohY7uVUbDBYwreRxf2Ex2x6yPYjEkyF7BMp/ZmSwHP9+Ya+xI4aGlN1R30+iPQYCaBsvyna2cJWC6QYA9BhLr/sYeOaAfwQ9co/OfNhjmQS7aX+EvhZ028jF/6WhGKI7vK7mbFXQPDbSRD2+jiEk+9lQvhxXfEIf0y1Wp/mutsmcw4o36lOc95eUXxRSZDkE1T4rdBFmvgChyINBWbUhBeiTo/jh9YaIpQ7/8++Z9w67jfBx6ir4dlZNG8jMqmIc0+eUFO5uBw20IO/RlVZeQFl/J8mNmT95fXXoFe3+pNtcqS6Ez2p5Nt30/uQjXoLedp5BH"
  template:
    type: Opaque
    metadata:
      name: {{ include "invoice-service.fullname" . }}-secret
      namespace: {{ .Release.Namespace }}
