apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "invoice-service.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
spec:
  encryptedData:
    # Encrypted placeholders - Run the following commands to update these:
    # echo -n "VALUE" | kubeseal --raw --name {{ include "invoice-service.fullname" . }}-secret --namespace {{ .Release.Namespace }}
    MONGO_URI: "AgBY7whX2Ntw/2IsYUK83ApFgiHYqAraHzvZNXR75bwja78zkFvAfgfqL1U2wsdYfJzp5ZuA/yrjo/mlgY+VraFqc9EZEDzDzmFAMbQEowLeQx56DO/1TjWEzSo0OgNQ+b9+c+euN1Y2mgq3VeGO9cNmCzssEoohle6fxWoERevpSWlX0NsSPuAAq9b6oBace/wVFu5vsawq+aLEUqpULCjH8u2EKV5wXswm/mjc0PccM0lnAA09KsTS6FlcpPKtDDewM4EGythBcXDnFBN3X5XbcWXG7IOlf4MvvujxlX6VNFh0A0hjuItTXMpWAykVowj36+Yy/l5R7bDO8JKBv1XfA0wQJZx5r7DDj/1SYEH2K7TrXUowWAClcUudCD5rnmfbhhBqo1riz6+ZMSIGd9jhYfmW0yVm3gwR2BXp/+5s7ha4mqNhvnjR7glHfWkDl2PPNMepaXLzh6D+zzkveXIow41GMYfu0ZVfGiw50uRwz3h0z7BZRlCsdUcacIjOAeZVRjBnXOJDv+UK05uuqCxHUcydZE7WEgneQb/BLYAOYJpoW/v0vFXvc/ug3rFFFFNVBKtu5AfdjXewiurznrrchd9pxnWPnuBxLEexiJakgVJT7swM38GsOxYxl6I7mmHl8dQm9mMflJZ0TkVlAH96XIa9/sM6BQLmMlyjorxNvQ5jLn/3JkOBxm1sfHBEUe57AD+dxEVUQPKLdw9f0hZJwbqHPaFwg4EAnT0DKmX1cjYKXi8trwb6lIzI29FG0eW/TRElK/AM1Iwl0Oo5AMdxAfg8ZmWHyHhia9F/NFPIbxXbspHJeRM="
  template:
    type: Opaque
    metadata:
      name: {{ include "invoice-service.fullname" . }}-secret
      namespace: {{ .Release.Namespace }}
