apiVersion: v1
kind: List
items:
  - apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: frontend-dev
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/Vaultrix-in/Vaultrix-Helm.git
        targetRevision: HEAD
        path: apps/frontend
        helm:
          valueFiles:
            - values-dev.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: vaultrix-dev
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
  - apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: api-gateway-dev
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/Vaultrix-in/Vaultrix-Helm.git
        targetRevision: HEAD
        path: apps/api-gateway
        helm:
          valueFiles:
            - values-dev.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: vaultrix-dev
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
  - apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: user-service-dev
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/Vaultrix-in/Vaultrix-Helm.git
        targetRevision: HEAD
        path: apps/user-service
        helm:
          valueFiles:
            - values-dev.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: vaultrix-dev
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
  - apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: order-service-dev
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/Vaultrix-in/Vaultrix-Helm.git
        targetRevision: HEAD
        path: apps/order-service
        helm:
          valueFiles:
            - values-dev.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: vaultrix-dev
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
  - apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: wallet-service-dev
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/Vaultrix-in/Vaultrix-Helm.git
        targetRevision: HEAD
        path: apps/wallet-service
        helm:
          valueFiles:
            - values-dev.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: vaultrix-dev
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
  - apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: invoice-service-dev
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/Vaultrix-in/Vaultrix-Helm.git
        targetRevision: HEAD
        path: apps/invoice-service
        helm:
          valueFiles:
            - values-dev.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: vaultrix-dev
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
  - apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: review-service-dev
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/Vaultrix-in/Vaultrix-Helm.git
        targetRevision: HEAD
        path: apps/review-service
        helm:
          valueFiles:
            - values-dev.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: vaultrix-dev
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
  - apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: notification-service-dev
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/Vaultrix-in/Vaultrix-Helm.git
        targetRevision: HEAD
        path: apps/notification-service
        helm:
          valueFiles:
            - values-dev.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: vaultrix-dev
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
