apiVersion: v1
kind: List
items:
  - apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: sealed-secrets-controller-dev
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: "-5"
    spec:
      project: default
      source:
        repoURL: https://github.com/Vaultrix-in/Vaultrix-Helm.git
        targetRevision: HEAD
        path: infra/dev
      destination:
        server: https://kubernetes.default.svc
        namespace: sealed-secrets
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

  - apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: vaultrix-infra-dev
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/Vaultrix-in/Vaultrix-Helm.git
        targetRevision: HEAD
        path: infra/dev
      destination:
        server: https://kubernetes.default.svc
        namespace: vaultrix-dev
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
  - apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: vaultrix-storage
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/Vaultrix-in/Vaultrix-Helm.git
        targetRevision: HEAD
        path: infra
        directory:
          include: storageclass.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
