replicaCount: 1

image:
  repository: ghcr.io/vaultrix-in/api-gateway
  pullPolicy: IfNotPresent
  tag: "96873"

service:
  type: ClusterIP
  port: 3000

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 10m
    memory: 64Mi

env: {}

