apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "user-service.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
spec:
  encryptedData:
    # Encrypted placeholders - Run the following commands to update these:
    # echo -n "VALUE" | kubeseal --raw --name {{ include "user-service.fullname" . }}-secret --namespace {{ .Release.Namespace }}
    # echo -n "VALUE" | kubeseal --raw --name {{ include "user-service.fullname" . }}-secret --namespace {{ .Release.Namespace }}
    MONGO_URI: "AgCSDyXBypr6hiQigqqHl7aXz1RZtJDUegNOGoN4V367cXQNvHMMDEDug3IKuo3ZSM3b+2R41unFpTjKFQQtoyUBNtxnp3Pz0SVI2Fi8UjP2UiDRbVDYG6V6vfROYbMxU7YhFA+dcGkGGkkOosKklCgbIWqb04HW2vrssspro0nC9BBqymkt4fVJvn3WQEFnKH0j5jY7P9EGWFBcXgOC1A4vuvmVj8JyVJmfNn3BFLojdUa1rKuhu5U8/RQooTbzC6vxBhArViNeUcSdmi0gdmHDUAp3i16A5KmaX+r5kiZ2LpxivNCWoBH7Nk/AwQTPa9580UomopX08At6WdfV5XxSD3hoRWRYCbUdGD8UUco26OcWjeEIxaxmBT3ewC55RetcISAkltlO5bQy5cD6zLvz4VIdE/lac+F4glhDt+i1VUbcdlrwbPaRgSrEWr05OGHE8rTeXlIT/lW178dVUus7vlGR26vXWC595F2k8vo50hQ+yv7EOvQvEvhYIRNtUdF3EpgvVhA/mtBWl8QODO0fOPaGkn4CbqZgQINzL89BdL0j5Vj3MOjLyl9YjD90dcmpbDAhERvT/7XhIm1uvM13ZV5PsATcnFRCd8tDqYGfgNDcde/6chmOdaJKYS9bYtLjMKs3R+y5ygnpS3DX+ylNfTuvf9/gH1vkL5RnzX55QuIr6RLUaNiIrY+Wsj6YYK75UoPpTOsn/AALswop5koD24V9H/DWfo8wJmenoqfJtKD4k+Ou7gk5u2RPlsWqnZ3g7t5fRDHKv7A+ahBXF+nxTSg+j5fvfd1jx7g8lHnbgXj6WiyY"
    JWT_SECRET: "AgBYZdg8LMfHAPZlyWoA3WLz5Jl9KVQjDDk4DGEDsxMv42VBRhi/dbCcpUVB6+AmXMuy2Zhu7nPUHsVmVDduQwFNKoPAKMY/wvSSSJUxDslM7yKHLKOir4+/d6HVGd+WVkA6ewU4vaHqTXUWHjwMV7D4gfujkObAi1On+aIKV34/XX8QqHOsaPneYHSnItYV1bjKNDlSmeSucIgNhsJj/OuJKHIo6FJWqZd1WaKU6X78QfHXcy/W02iq4eBU2e6iHLUEX9s4rY4zJhQRx85CSihvO6x5AZWqSVa/jugcLvZLKl6ZUallfpQ7K6hUgtcwDHAVH5EJtU6zYW2cMuiYJl5EweChY9r96FJrt4XDzokU4JHREwtlJjBb3xTWnbs8kb3OR8oQDJ7H6Tn/vBoldaUgHj1YlLyWfHM2lkSc2c+Qe6RCjc0hP+fJ8yfNo85laM+2sW/01UGjMkzpxtj5ldEinR7hzQj0VS5Phm8LW6S3pg0aMyes12KjioiueptU7pWu0ahHXEu7i+9gGVeSSX+Bw3RQRRjeWfzMv3OkGPPyh1wKdmPDRfXDxja8W2F+VAB/0jiebyuXnf5mfK5By2q8cTnLrAmWhomI9ng7Tkx+oxIvghwU2JMCcykX/fEQbFIJgfYpETAKYzVxn8+xqp74B2nqd33pt8Nwz+SE0XgSF4plNFf/iowWprGMJvsHuAmgH4lw0xkDQccC5WKa"
  template:
    type: Opaque
    metadata:
      name: {{ include "user-service.fullname" . }}-secret
      namespace: {{ .Release.Namespace }}
