apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "user-service.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
spec:
  encryptedData:
    # Encrypted placeholders - Run the following commands to update these:
    # echo -n "VALUE" | kubeseal --raw --name {{ include "user-service.fullname" . }}-secret --namespace {{ .Release.Namespace }}
    # echo -n "VALUE" | kubeseal --raw --name {{ include "user-service.fullname" . }}-secret --namespace {{ .Release.Namespace }}
    MONGO_URI: "AgCQ6TWXqPMBQlursmrwSkym7jw9mmgqzdJWiW1YfR/p/vIWMN7Hekri+l2LPaRBq6q4G6JtWYA9Pj5d0urIwZhwr6xzB4agHRspTrHchkBYpuaw18ups4fqlpsFGBPyDHBQA6I2AWe9vHDBP7RMVRi5P8qoMT/CAwV+I6B2PNpP3dBRIAgJ8QVyQx0HIj/O2edw7zSB07+d1FhgOtCsg1xlD35ZvJAEBjkRdqkJfW1gETeRDCMB3p6ccBMiW86lKTUex2bBgFEEF1wbLd8eVa/80o9hfjtxHIQBMs4M9tBXC444cOSobvqvydVFaOw0kxm8Aftq1OxoVpw2e/sLWBTsR3GmijPyz+x4XqEYrcW94aNDvzmrr3VexVsl+Wm8GeMMkehw2hQT0ooli8glbvJSO4cjL1SuAGL73aITUH6671WpyV3qppXRH6AwL6GqzgXP3UrJTl7Wcc5JASKkq9pKADi16vtaWZPSTlbyBFJz0s0lEnePvZn7+j3rPrEteOZvndW+wnZIEG+jRMBCSX+qdcZ3Wt2W3xgrK5jk8bzxeUmF4Ul5wdFdeAIa/0EYLxo5qE9gju7Jb8naig62uJX9JYWaNwLbzTIaAewnCPizBN0riLBROOFU9NyW0VP3zwrio5f/tVwP35Lvzqc5KE+DG17BL5uNXB5PHP67cgwnTZMO/DB6ThYYH7MH4dLbqymlqYfOIldl1bvbSzSEAV4v2TDL3YJWNpLZlcNTbyvJDA1jtt+xJ/kMHbXFvztQFMnIHUalGOHf9Gc1sya7COg9HjzmLggO"
    JWT_SECRET: "AgBYZdg8LMfHAPZlyWoA3WLz5Jl9KVQjDDk4DGEDsxMv42VBRhi/dbCcpUVB6+AmXMuy2Zhu7nPUHsVmVDduQwFNKoPAKMY/wvSSSJUxDslM7yKHLKOir4+/d6HVGd+WVkA6ewU4vaHqTXUWHjwMV7D4gfujkObAi1On+aIKV34/XX8QqHOsaPneYHSnItYV1bjKNDlSmeSucIgNhsJj/OuJKHIo6FJWqZd1WaKU6X78QfHXcy/W02iq4eBU2e6iHLUEX9s4rY4zJhQRx85CSihvO6x5AZWqSVa/jugcLvZLKl6ZUallfpQ7K6hUgtcwDHAVH5EJtU6zYW2cMuiYJl5EweChY9r96FJrt4XDzokU4JHREwtlJjBb3xTWnbs8kb3OR8oQDJ7H6Tn/vBoldaUgHj1YlLyWfHM2lkSc2c+Qe6RCjc0hP+fJ8yfNo85laM+2sW/01UGjMkzpxtj5ldEinR7hzQj0VS5Phm8LW6S3pg0aMyes12KjioiueptU7pWu0ahHXEu7i+9gGVeSSX+Bw3RQRRjeWfzMv3OkGPPyh1wKdmPDRfXDxja8W2F+VAB/0jiebyuXnf5mfK5By2q8cTnLrAmWhomI9ng7Tkx+oxIvghwU2JMCcykX/fEQbFIJgfYpETAKYzVxn8+xqp74B2nqd33pt8Nwz+SE0XgSF4plNFf/iowWprGMJvsHuAmgH4lw0xkDQccC5WKa"
  template:
    type: Opaque
    metadata:
      name: {{ include "user-service.fullname" . }}-secret
      namespace: {{ .Release.Namespace }}
