apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "user-service.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
spec:
  encryptedData:
    # Encrypted placeholders - Run the following commands to update these:
    # echo -n "VALUE" | kubeseal --raw --name {{ include "user-service.fullname" . }}-secret --namespace {{ .Release.Namespace }}
    # echo -n "VALUE" | kubeseal --raw --name {{ include "user-service.fullname" . }}-secret --namespace {{ .Release.Namespace }}
    MONGO_URI: "AgA4ly+3L+hM1GM5mpEQ7F9cpQLn+FJnuLENggUR9BZtOOnVOCKEIqleFzlhoDUuZIK1zLWKbBETw10HSdEecC71KanCj3FbekEm0tHGJpbGAetzv0/Sn6Hte1DlpXQX+VTxWFTUfM/0SuS6ptx930T7zkzBvjAN8e0nPN9MTO4vp8HigkUlS4asB1tm0ebnnL9XEQVxRYOZ9Fc534U4GL5RK8c+tRF4Prq3GhIvfjhuShyvtf2eThrmQoSs5ZG6bu4EuKluxX0wEKu8Zx7FB/fMRZfsnZIksqeqrD5SWo8TFNsthBscXj1VCNPxnm6AePBkseW61cY+2SG4ilUO7EiZb7lDM1I8ptYw7amnxmltO1gE5SJsi8vc2v2FPmvB9s4VV3+cR/PaErc1saJ/qKxK7JIJStB41a6LZFQR2tRYkdQ2pNtAw9J/OYzkj9ld8sup8z2e3WvUun5zonhS9WQtiAnpQmX6K3nSvR/MFYWxsG3InJoSQxTvNzIuXGAr8yyaQN1s/WLBZYwHt3iD/nIXCM8qVRw4bpGOHS1qwMMdNQkaobL3BUk5OiCgUYWk0F0kVBsRz9M2sCYOrBmUdYQ22QZkUo45jS184dLTY/zUgLevJDT9WmjPJddJkU3kuuhnwhOnTtdKLCQ/pufVWnb4FwIgR0gDYnNQROwlyVGYBRsIGmJYDk9/Tce7Czqzs0FCRv4jb9Hh3CG3lqwQUDZXNJzW+8UF/Rx9UUX+Ln+i6la3XCFQzAPePQ4744rcVjZfi7VXrx6oReMnXbBWkiQ+L9a6p/9U5CYzdVA8kg=="
    JWT_SECRET: "AgBYZdg8LMfHAPZlyWoA3WLz5Jl9KVQjDDk4DGEDsxMv42VBRhi/dbCcpUVB6+AmXMuy2Zhu7nPUHsVmVDduQwFNKoPAKMY/wvSSSJUxDslM7yKHLKOir4+/d6HVGd+WVkA6ewU4vaHqTXUWHjwMV7D4gfujkObAi1On+aIKV34/XX8QqHOsaPneYHSnItYV1bjKNDlSmeSucIgNhsJj/OuJKHIo6FJWqZd1WaKU6X78QfHXcy/W02iq4eBU2e6iHLUEX9s4rY4zJhQRx85CSihvO6x5AZWqSVa/jugcLvZLKl6ZUallfpQ7K6hUgtcwDHAVH5EJtU6zYW2cMuiYJl5EweChY9r96FJrt4XDzokU4JHREwtlJjBb3xTWnbs8kb3OR8oQDJ7H6Tn/vBoldaUgHj1YlLyWfHM2lkSc2c+Qe6RCjc0hP+fJ8yfNo85laM+2sW/01UGjMkzpxtj5ldEinR7hzQj0VS5Phm8LW6S3pg0aMyes12KjioiueptU7pWu0ahHXEu7i+9gGVeSSX+Bw3RQRRjeWfzMv3OkGPPyh1wKdmPDRfXDxja8W2F+VAB/0jiebyuXnf5mfK5By2q8cTnLrAmWhomI9ng7Tkx+oxIvghwU2JMCcykX/fEQbFIJgfYpETAKYzVxn8+xqp74B2nqd33pt8Nwz+SE0XgSF4plNFf/iowWprGMJvsHuAmgH4lw0xkDQccC5WKa"
  template:
    type: Opaque
    metadata:
      name: {{ include "user-service.fullname" . }}-secret
      namespace: {{ .Release.Namespace }}
