apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "user-service.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
spec:
  encryptedData:
    # Encrypted placeholders - Run the following commands to update these:
    # echo -n "VALUE" | kubeseal --raw --name {{ include "user-service.fullname" . }}-secret --namespace {{ .Release.Namespace }}
    # echo -n "VALUE" | kubeseal --raw --name {{ include "user-service.fullname" . }}-secret --namespace {{ .Release.Namespace }}
    MONGO_URI: AgBy3iG...[SEALED_DATA_FOR_MONGO_URI]...
    JWT_SECRET: AgBy3iG...[SEALED_DATA_FOR_JWT_SECRET]...
  template:
    type: Opaque
    metadata:
      name: {{ include "user-service.fullname" . }}-secret
      namespace: {{ .Release.Namespace }}
