apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "user-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
spec:
  encryptedData:
    # Encrypted placeholders - The user must run kubeseal to update these with real values
    # Command: echo -n "Vaultrix@123!" | kubeseal --raw --name {{ include "user-service.fullname" . }} --namespace {{ .Release.Namespace }}
    MONGO_URI: AgBy3iG...[SEALED_DATA]...
    JWT_SECRET: AgBy3iG...[SEALED_DATA]...
  template:
    type: Opaque
    metadata:
      name: {{ include "user-service.fullname" . }}
      namespace: {{ .Release.Namespace }}
