apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "wallet-service.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
spec:
  encryptedData:
    # Encrypted placeholders - Run the following commands to update these:
    # echo -n "VALUE" | kubeseal --raw --name {{ include "wallet-service.fullname" . }}-secret --namespace {{ .Release.Namespace }}
    MONGO_URI: "AgCebknd8RmV73vst7qI9PZYFDPXeFMcLtIIK5k0e9haTcb5iZjuecDSasgfyzmQdkVTNTgFDb9QgkjlRUuuBGiFcB9PtCMuNul7f8LnjCfuf0uwYcnnlno40IJgT4Pa9HG9ZNeV6C6CK7VWCaWBCbDIJcCOgpl9kLbadd7cQzwI6isolvINYXZBfOxYwisvlwBiVE5p+J9AOKw57H3bR2rZptvlB7hMMx3p1iRmqGgNnSkho9u9vUFRULm7myulNpnATbs+LRXPIkQ3OC6GxlENW/IhzehQ882hgwln/xq6N3FFDDPGAdvNkAhRkoDHKX+o+p3jCbzdwWo2nFlUvHkkZgbQ0Gmhf77MgWYvb4c0j7AbRf4bp7YX43xL7CLBXXiEIRWcwQn2AYPdja8STa248QSOen6P0RyKx8Bb0vmx3N28my2K2OoP/eWJid6FW13odhirZp7FbgAGDsHKiPPn8a2NArPq59X4RddY2qjqsl6tDmKByTNqHmsFRl5Y90iz+wznHvN8w2hY53s9qXsLhLZ+j+Z1p1TuAD5epxjXy9bwLLUoF8YPemfWH8rBEjnVTHKnOLWFhULzixCntPJ/jFQ4jkR8rEdGHOpXs7lShSGH0AYlH+oBnPNJhHH+ftu6V7PX7DeFhsZ2xkR7cdlIhITxd9JNyp+VFVPpOE4rrDfk1dkzuNRRqBySfdFBxgqr5AHqS4nzE0bHENtPK+9xUFPwRJ83C0A3H0z5jwr50/dJPVLQrEpBw/da49rfFE7gYeigDy9EfiQBHK2ISFfOzv9/R4dtM/+TkFaqNXg="
  template:
    type: Opaque
    metadata:
      name: {{ include "wallet-service.fullname" . }}-secret
      namespace: {{ .Release.Namespace }}
