apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "wallet-service.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
spec:
  encryptedData:
    # Encrypted placeholders - Run the following commands to update these:
    # echo -n "VALUE" | kubeseal --raw --name {{ include "wallet-service.fullname" . }}-secret --namespace {{ .Release.Namespace }}
    MONGO_URI: "AgBLl6l1RAEAC0Dc3N9+xg5Pa3YVhRFisSTtxvsDeIwEYplGx70WyuqwLBM6VwVK0QKc6XlDn/2ajUqYUiFUKZXE7YN6y9o6yP5kuu2fScvyM3s95pRcvunMAwTmQl2wlw3SYenMAwqm+xd2KYJQhyR5JebN6NtQJNpvf63N9UtIlYOKzH/lL1iD+LWrUZQgW9Dhnv5+YQ8U0CzO8yPwcGkFfeiZbvXe62qqfIsjptTPfoxgTu3pmjo6Y4TKLMYQzDuO6uvECD13++ET6jJAjL3NL85Qu6iqViyMZ4lkBF0Sff3G78EQY4NLMryXRdG1+tG509WBnTqETNNI2ZFnqytIBwGRkoeg303IT0K89QYroX0y+8HKzlevN0Y5FrFc3YBhF8S3upv77X8nISQ/tLsveX52EiuNpmUKWKgQKj6mZlG/MesxmVeZwDk460nu0rSbBGrza9iSxMPvoIorNjZtj8rrzfzApAVj3s5weJb06wGGukFmCXdJeJHkWeJm5ip9YP29HerJdMl/ebnnzCxkwz6UnhpJn0UHpwMTEbEgYqZqcWyXO//AOA7jNzFks2B7MiV0PsCuJ8y6mLWTYom2WuiZmdsoIERvO7zeVO6iFCQYGjiEAqPSQqEbpTOCTxNh1Lsjfh9whDP5A3DpWgdsvVi+rq06wvR0YLjmtIA6xq+xlwAFLy+1E1QHH/Ot2KTnVxQu6AmP/OMv12YU15TRMXsHCaBlg41FVDhWAGjtUvGpsb42UvLfpJofaIyQiMZub9xa1ZzFR4r/B8WX7D0PAq3xo3zPV8sbT0u0HQB73KVDnEsA3A=="
  template:
    type: Opaque
    metadata:
      name: {{ include "wallet-service.fullname" . }}-secret
      namespace: {{ .Release.Namespace }}
