apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "wallet-service.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
spec:
  encryptedData:
    # Encrypted placeholders - Run the following commands to update these:
    # echo -n "VALUE" | kubeseal --raw --name {{ include "wallet-service.fullname" . }}-secret --namespace {{ .Release.Namespace }}
    MONGO_URI: "AgARfOXYSByNAVyzpOfV05kUk4DOoMLps5o/YBiLCaJxAZSDrDw2yvv9dCANSMzzG/GboFIraFjJvFxAlc7DoxGIh3tLiqB2QS1GjH8vLwKIKSy4S3I61PrU9VJ4PuNgaWLTgkUJ47s8rgf4PxMtrX5emBIwti/+sPJdmo9heTpBsLGI/xg5txEwLZDdV6Sms4+bHV0EF5byy3JGTjVYjqu2zpvXVUDeDS6r5a4Zrw6nB6DSmHGvBl/1em+EXMFy8G3xVzpB0J1Z6kT66fg9AkEZpoHL7GyJp3t56bZ5uw/pTeseZlXk07UtYNC3ELSM/EztEgX/Moq1xQVj4DMRZBQVPtidybINqFSnsweRbTZAlVLUdX75N4XbkLirVkF9+iKgpqvq7pte/4Unm3uSxcFH74MnnvmGmK03xEKx2WRk3zcRerr4W28c5017Qy4o2Af8ycbCBpeN7rip/WUEkf5e2HGAI4yKxRpzRJMctn9/fe1iTNQEGKCSNeFFyaqk9YXOtNs4Ku/AsL3uX8MHlGYIUZhAZI+RoSvcwQ67Ar/dz80yVFrEbIZnumvKuMwrdhSg7bnAHIRMeym/q1xuh3igg6VmvopIPuXSQznSf/Jm/pQ1ZN1ETF+QTd5X0VMdafOzVYZawSzzHUC4TyIMtNt0SwU/LnRJcMbok3Kv8HZMPzaxKITDcleiiZQmhDz4Tz73NZNCNW8PO5+ASgkJprGn7XPnj9+u/u7e4hZ9CrM/QyU9Zjr1dYmqGMlv4nFNV8HRZmZFRY7wFrtuRJqohEMjOazSaGYy8w=="
  template:
    type: Opaque
    metadata:
      name: {{ include "wallet-service.fullname" . }}-secret
      namespace: {{ .Release.Namespace }}
