apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "notification-service.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
spec:
  encryptedData:
    # Encrypted placeholders - Run the following commands to update these:
    # echo -n "VALUE" | kubeseal --raw --name {{ include "notification-service.fullname" . }}-secret --namespace {{ .Release.Namespace }}
    # echo -n "VALUE" | kubeseal --raw --name {{ include "notification-service.fullname" . }}-secret --namespace {{ .Release.Namespace }}
    # echo -n "VALUE" | kubeseal --raw --name {{ include "notification-service.fullname" . }}-secret --namespace {{ .Release.Namespace }}
    # echo -n "VALUE" | kubeseal --raw --name {{ include "notification-service.fullname" . }}-secret --namespace {{ .Release.Namespace }}
    # echo -n "VALUE" | kubeseal --raw --name {{ include "notification-service.fullname" . }}-secret --namespace {{ .Release.Namespace }}
    MONGO_URI: "AgCVKeLxLkP6w2H1B4R8O9hWG6vLv2voDBhflrwFhuqGOgkIzio8JqIpBygks8Zh9a+QCmQm34BDZtL2scfXpuJEP2c4vRRf5RpAEUB2wyh2QwYqpp5ejb9sX0KOjste10jOWtmhYkEGd6/9WYNBt6uHW58P0VFQj91MCNRhn/PFO/XZwZBHKxJMjp37tZ0uAiZwGeS40vkNF66wtZGk8idJS00ypTXvRTkAZXUbqUF305Y0/FLYyfRIP98B5aP+pOzcw2fmqBD+Phwzw7YO2d9SxigwRTfxdjL6DmXXo6vN/2oY8sYeLlKmyY8/KcJVi9xmAnwjj/gPEyyonoBQwaZmrOiX64Xwfu4pTtdyuWdrc4IR3PkonGvT/98zLCaBq4hz58/KkjvT6bp7nGNW3rUzcu5Beml7VbMvXs3ie23zQ9oSh0BlB+kgeQTs6i0q4RqwX4+CYH64knmlpCf29b2ucADyklKLdm+qrqmiICWRP0cNyJq7wC+PEZp/AUaKU+eBD7E5Pal2D74ak8XaRTEDVRhdTNLvfrlwRvKXHlvFguakqCTmPO9MI2z/PSxJzwToy4bkbKzOb23ic7Hy8mhr2nDNFVQyMri0e73SKDoXniteg/LeHLhCTSnbxOOi0/kK2yrHJQZoPB/Gz6p1xI5vhnUQopzTLLxRHjbn514DTWvufVToJ68FA8tatGFr7SY9Q6BZ4fyJV0lTXHEK193W96/lsBYhJ822vKvoNjOkC9Y1Wrpkip1Op0CcPBud3SYiW1G3lymacBKvIQdsUytV8YXw4VSivbqS5FWKrjqdlvHhsNE="
    SMTP_HOST: AgBy3iG...[SEALED_DATA_FOR_SMTP_HOST]...
    SMTP_PORT: AgBy3iG...[SEALED_DATA_FOR_SMTP_PORT]...
    SMTP_USER: AgBy3iG...[SEALED_DATA_FOR_SMTP_USER]...
    SMTP_PASS: AgBy3iG...[SEALED_DATA_FOR_SMTP_PASS]...
  template:
    type: Opaque
    metadata:
      name: {{ include "notification-service.fullname" . }}-secret
      namespace: {{ .Release.Namespace }}
